name: CI/CD Pipeline for Mock Repo

on:
  push:
    branches:
      - main
      - feature/ci-cd-setup
  pull_request:
    branches:
      - main
      - feature/ci-cd-setup

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint ruff

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run pylint
      run: pylint **/*.py

    - name: Run ruff
      run: ruff check **/*.py

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv sync --all-extras

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv sync --all-extras

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run tests
      run: uv run python -m pytest tests

  security_scan:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety

    - name: Run Bandit
      run: bandit -r app

    - name: Run Safety
      run: safety check

  dependency_management:
    runs-on: ubuntu-latest
    needs: security_scan

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install pip-tools
      run: pip install pip-tools

    - name: Compile requirements
      run: pip-compile

  containerize:
    runs-on: ubuntu-latest
    needs: dependency_management

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker compose up -d

# deploy:
#   runs-on: ubuntu-latest
#   needs: containerize

#   steps:
#   - name: Checkout code
#     uses: actions/checkout@v3

#   - name: Deploy to OpenShift
#     run: |
#       oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOKEN }}
#       oc project myproject
#       oc start-build aurora-nlp --from-dir=. --follow

# notify:
#   runs-on: ubuntu-latest
#   needs: [lint, build, test, security_scan, dependency_management, containerize]

#   steps:
#   - name: Send Teams notification
#     run: |
#       curl -H 'Content-Type: application/json' -d '{"text": "Pipeline completed successfully"}' ${{ secrets.TEAMS_WEBHOOK_URL }}